# Generated by Django 3.1.4 on 2021-01-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_appoint_doctor_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoint',
            name='birthdate',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.FileField(blank=True, default='default.jpg', upload_to='medico_expert/images/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.FileField(blank=True, default='default.png', upload_to='medico_expert/images/'),
        ),
    ]
