# Generated by Django 3.1.4 on 2021-01-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20210104_1209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appoint',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
