# Generated by Django 3.1.4 on 2021-01-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_appoint_doctor_patient_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appoint',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
